//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_Mvc5Entities1 : DbContext
    {
        public Db_Mvc5Entities1()
            : base("name=Db_Mvc5Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_deneyimlerim> tbl_deneyimlerim { get; set; }
        public virtual DbSet<tbl_egitimlerim> tbl_egitimlerim { get; set; }
        public virtual DbSet<tbl_hakkimda> tbl_hakkimda { get; set; }
        public virtual DbSet<tbl_hobilerim> tbl_hobilerim { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_sertifikalarim> tbl_sertifikalarim { get; set; }
        public virtual DbSet<tbl_yeteneklerim> tbl_yeteneklerim { get; set; }
        public virtual DbSet<tbl_sosyalmedya> tbl_sosyalmedya { get; set; }
    }
}
